### ISSUE TITLE
Mail queue

### ISSUE THREAD

**Issue by PenDragoon** [abrigham1/laravel-email-exceptions#10]
How can i send laravel error mail with queue?
Send online is too slow.

**Comment by abrigham1** [comment]
There's no way to hook into laravel's mail queuing currently however you are certainly welcome to make a pull request. I don't view it as a huge issue as these emails are only going out when the site is having errors anyway so the user typically isn't getting what they want at the end of the load time already.

**Comment by ebarquero85** [comment]
It issue should be closed.
