### ISSUE TITLE
Request add user information

### ISSUE THREAD

**Issue by Andicot** [abrigham1/laravel-email-exceptions#11]
Can you implements User logged information, if one user is logged.

Thanks

**Comment by abrigham1** [comment]
@Andicot You should be able to modify the blade template if you've published it and add that as suggested here: https://github.com/abrigham1/laravel-email-exceptions/issues/6#issuecomment-499916709

**Comment by ebarquero85** [comment]
In: `resources/views/vendor/laravelEmailExceptions/emailException.blade.php`

you can add:
```html
...
<tr>
    <td>
        <strong>User:</strong>
    </td>
    <td>
        @if (Auth::User())
            {{ Auth::User()->UsuarioId }}
        @endif
    </td>
</tr>
...
```

**Comment by Andicot** [comment]
Thank’s, I done.
