### ISSUE TITLE
[Question] - Laravel 6.2

### ISSUE THREAD

**Issue by KaminoU** [abrigham1/laravel-email-exceptions#12]
Hello,

I have installed your package, with the told configuration but my Laravel does not send email on Exceptions.

I have also verified all that my mail settings work well and I got new mail with a simple Mail::to()...;

My Laravel version is 6.2, and as you do not mention anything about the 6.x version, do you know if there is any problem with running your package on the 6.x laravel version?

Thank you for reading and also thx for your package =)

**Comment by abrigham1** [comment]
Hi @KaminoU yes please try pulling the 2.0 tag for laravel 6.X let me know if you have any issues (I still need to update the documentation for this)

**Comment by KaminoU** [comment]
work like a charm @abrigham1 =)

thank you ^^
