### ISSUE TITLE
No hint path error on 5.4

### ISSUE THREAD

**Issue by subdesign** [abrigham1/laravel-email-exceptions#3]
I get the following error on Laravel 5.4:

> PHP Fatal error:  Uncaught InvalidArgumentException: No hint path defined for [laravelEmailExceptions].

especially when I want to run `php artisan config:cache`

Any idea what's the prob? Thanks

EDIT: the package sends the errors by email, but I can't use other functions because of this error..

```
Stack trace:
#0 /var/www/portfolio-conference/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(90): Illuminate\View\FileViewFinder->parseNamespaceSegments('laravelEmailExc...')
#1 /var/www/portfolio-conference/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(76): Illuminate\View\FileViewFinder->findNamespacedView('laravelEmailExc...')
#2 /var/www/portfolio-conference/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\View\FileViewFinder->find('laravelEmailExc...')
#3 /var/www/portfolio-conference/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(310): Illuminate\View\Factory->make('laravelEmailExc...', Array)
#4 /var/www/portfolio-conference/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(283): Illuminate\Mail\Mailer->renderView('laravelEmailExc...', Array)
#5 in /var/www/portfolio-conference/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 112
```

**Comment by abrigham1** [comment]
Have you added the service provider to your config/app.php providers array?

ex.

`
'providers' => [
    /*
     * Package Service Providers...
     */
    Laravel\Tinker\TinkerServiceProvider::class,
    Abrigham\LaravelEmailExceptions\EmailExceptionsServiceProvider::class,
],
`

If so what other things are you trying to do with it? Are you overriding views or anything like that?

**Comment by subdesign** [comment]
Somehow it disappeared, I guess composer dump was the key

**Comment by abrigham1** [comment]
Happy to hear its been resolved thanks for the update!
