### ISSUE TITLE
Send mail in Localhost

### ISSUE THREAD

**Issue by bipin244** [abrigham1/laravel-email-exceptions#4]
I don't received any mail when i run my project in my local server

**Comment by abrigham1** [comment]
What are you using as a mail server? Have you tried using mailtrap as explained in the [Gotchas](https://github.com/abrigham1/laravel-email-exceptions#gotchas). Is your laravel install able to send out mail outside of this package or is sending mail not working in general for your project?

**Comment by abrigham1** [comment]
Is this still an issue for you?
