### ISSUE TITLE
Send cc Exception mail

### ISSUE THREAD

**Issue by dfuentes141** [abrigham1/laravel-email-exceptions#5]
It's posible send cc of the mail exception?

**Comment by abrigham1** [comment]
@dfuentes141 Yes it should be you can do it one of two ways either use a mailing list:

`'toEmailAddress' => devs@mydomain.com,`

where devs@mydomain.com is a mailing list set up to send out to all your devs (or whoever you want to receive the email)

If you don't have access to set up a mailing list then you can also just pass an array for the toEmailAddress field like this:

`'toEmailAddress' => ['dev1@example.com', 'dev2@example.com', 'dev3@example.com'],`

Let me know if this resolves your issue.

**Comment by abrigham1** [comment]
I'll update the documentation to make it more clear that toEmailAddress can accept an array as well.

**Comment by dfuentes141** [comment]
Great, thanks for the tip
