### ISSUE TITLE
Session data in emailException.blade.php

### ISSUE THREAD

**Issue by karan101292** [abrigham1/laravel-email-exceptions#6]
Hi, I want to send user details with error mail. I am using `Session::get('users')['id']` syntax to do the same in other blade.php files to print user id but in **emailException.blade.php** its not getting printed.

**Comment by ebarquero85** [comment]
This is what I do in **emailException.blade.php**, you do not need to use session to get the user:

```php
{{ Auth::User()->id }}
```
or:

```php
{{ Auth::User()->username }}
```

@abrigham1 you should close this issue, is too old.

**Comment by abrigham1** [comment]
Closing with @ebarquero85 suggestion for a workaround
